from pathlib import Path

path = Path('services/workers/src/services/prospecting/offer_matcher.py')
text = path.read_text()
old = '''        if strong_evidence and not strong_matched:\n            cap = int(quality_gates.get("max_score_without_strong_evidence") or 100)\n            if score > cap:\n                score = cap\n                capped_by.append("missing_strong_evidence")\n        if min_observed and observed_count < min_observed:\n            cap = int(quality_gates.get("max_score_with_sparse_evidence") or 100)\n            if score > cap:\n                score = cap\n                capped_by.append("sparse_evidence")'''
new = '''        if strong_evidence and not strong_matched:\n            cap = int(quality_gates.get("max_score_without_strong_evidence") or 100)\n            if score > cap:\n                score = cap\n            capped_by.append("missing_strong_evidence")\n        if min_observed and observed_count < min_observed:\n            cap = int(quality_gates.get("max_score_with_sparse_evidence") or 100)\n            if score > cap:\n                score = cap\n            capped_by.append("sparse_evidence")'''
assert text.count(old) == 1
text = text.replace(old, new, 1)
path.write_text(text)

path = Path('services/workers/src/services/alphamec_vertente_equalization.py')
text = path.read_text()
insert_after = '''def _enhance(registry: OfferProfileRegistry, key: str, *, version: str = "2.1", **sections: dict[str, Any]) -> None:\n    profile = registry.get(key)\n    if profile is None:\n        return\n    registry.register(replace(\n        profile,\n        version=version,\n        offer=_merge(profile.offer, sections.get("offer") or {}),\n        icp=_merge(profile.icp, sections.get("icp") or {}),\n        discovery=_merge(profile.discovery, sections.get("discovery") or {}),\n        prescoring=_merge(profile.prescoring, sections.get("prescoring") or {}),\n        enrichment=_merge(profile.enrichment, sections.get("enrichment") or {}),\n        signals=_merge(profile.signals, sections.get("signals") or {}),\n        intent=_merge(profile.intent, sections.get("intent") or {}),\n        decision_makers=_merge(profile.decision_makers, sections.get("decision_makers") or {}),\n        channels=_merge(profile.channels, sections.get("channels") or {}),\n        qualification=_merge(profile.qualification, sections.get("qualification") or {}),\n        outreach=_merge(profile.outreach, sections.get("outreach") or {}),\n    ))\n\n\n'''
helper = '''def _set_signal_roles(\n    registry: OfferProfileRegistry,\n    key: str,\n    *,\n    positive: list[str],\n    optional_positive: list[str],\n    negative: list[str],\n) -> None:\n    \"\"\"Separa fit comercial de sinais auxiliares sem misturar disponibilidade de contato.\"\"\"\n    profile = registry.get(key)\n    if profile is None:\n        return\n    signals = dict(profile.signals or {})\n    signals["positive"] = list(dict.fromkeys(positive))\n    signals["optional_positive"] = list(dict.fromkeys(optional_positive))\n    signals["negative"] = list(dict.fromkeys(negative))\n    registry.register(replace(profile, signals=signals))\n\n\n'''
assert text.count(insert_after) == 1
text = text.replace(insert_after, insert_after + helper, 1)

marker = '''    for key in ("trophies_sports", "trophies_mej"):\n'''
roles = '''    # Sinais de fit primários representam necessidade comercial. CNPJ, telefone\n    # e e-mail ajudam na execução, mas não devem ser a razão principal do fit.\n    _set_signal_roles(\n        registry,\n        "mechanical_project",\n        positive=["HAS_PRODUCTION_LINE", "CUSTOM_MACHINERY", "AUTOMATION", "EXPANDING_FACTORY", "NEW_EQUIPMENT", "HIRING_MECHANICAL_ENGINEER"],\n        optional_positive=["HAS_CNPJ", "HAS_BUSINESS_EMAIL", "HAS_PHONE"],\n        negative=["RETAIL_FOCUSED", "SERVICE_ONLY"],\n    )\n    _set_signal_roles(\n        registry,\n        "technical_drawing",\n        positive=["CUSTOM_PARTS", "REVERSE_ENGINEERING", "CUSTOM_MANUFACTURING", "USINAGEM", "REPLACEMENT_PARTS"],\n        optional_positive=["HAS_CNPJ", "HAS_BUSINESS_EMAIL", "HAS_PHONE"],\n        negative=["RETAIL_FOCUSED", "SERVICE_ONLY"],\n    )\n    _set_signal_roles(\n        registry,\n        "machine_manual",\n        positive=["MACHINE_MANUFACTURER", "NEW_MACHINE", "NR12", "TECHNICAL_DOCUMENTATION", "INDUSTRIAL_SAFETY"],\n        optional_positive=["HAS_CNPJ", "HAS_BUSINESS_EMAIL", "HAS_PHONE"],\n        negative=["RETAIL_FOCUSED", "SERVICE_ONLY"],\n    )\n    _set_signal_roles(\n        registry,\n        "trophies",\n        positive=["EVENT_SCHEDULED", "HOSTS_EVENTS", "SEASONAL_DEMAND", "CUSTOM_PRODUCTS"],\n        optional_positive=["HAS_INSTAGRAM", "HAS_PHONE"],\n        negative=["ONLINE_ONLY_RESALE"],\n    )\n\n'''
assert text.count(marker) == 1
text = text.replace(marker, roles + marker, 1)
path.write_text(text)
