# Re-exporta modelos dos workers (fonte única para o modelo de dados)
import sys
import os

# Adiciona workers src ao path para importar modelos
workers_path = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'workers', 'src')
sys.path.insert(0, workers_path)

from database.models import (
    Lead,
    LeadOpportunityRow,
    EventOpportunityRow,
    CommercialOutcomeRow,
    Campaign,
    PrescoringDiscard,
    Enrichment,
    Message,
    FollowUp,
    FollowUpVersion,
    MessageChannel,
    Job,
    User,
    Notification,
    NotificationType,
    Contact,
    CompanyRecord,
    Conversion,
    Organization,
    OrganizationMember,
    Invite,
    LeadActivity,
    LeadActivityAction,
    LeadStatus,
    ScoringFeedback,
    TemplateLearning,
    FeedbackDirection,
    FeedbackStatus,
    CampaignStatus,
    JobStatus,
    JobType,
    AnalysisProfile,
    LeadPriority,
    ContactRole,
    OrganizationRole,
    SalesRole,
    CampaignScoringTemplate,
    OrganizationSecret,
    FollowUpStep,
    FollowUpStatus,
    OnboardingStatus,
    EmailSuppression,
    NegotiationStage,
    ContractOutcome,
    PostSaleChannel,
    LostReason,
    SalesTarget,
    OrgAuditLog,
    OrgAuditEvent,
    ConsultantPlaybook,
    Company,
    Person,
    WebhookLog,
)
